name = "shfmt"
type = "cli"

[platform.linux]
download-file = "shfmt_v{version}_linux_{arch}"

[platform.macos]
download-file = "shfmt_v{version}_darwin_{arch}"

[platform.windows]
download-file = "shfmt_v{version}_windows_{arch}.exe"

[install]
checksum-url = "https://github.com/mvdan/sh/releases/download/v{version}/sha256sums.txt"
download-url = "https://github.com/mvdan/sh/releases/download/v{version}/{download_file}"
                
[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"
x86 = "386"

[resolve]
git-url = "https://github.com/mvdan/sh/"
git-tag-pattern = "v((\\d+)\\.(\\d+)\\.(\\d+))"
